<a href="https://colab.research.google.com/github/KaranYadav6041/SRM-AIML-D-RA2411026030211-/blob/main/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data={
    "Name":["Ajay","Alex","Arun","Aman","Anam"],
    "Age":[23,25,63,22,20],
    "Gender":['M','M','M','M','F']
}

In [ ]:
df=pd.DataFrame(data)
df.head()

   Name  Age Gender
0  Ajay   23      M
1  Alex   25      M
2  Arun   63      M
3  Aman   22      M
4  Anam   20      F

In [ ]:
df.info(data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Gender  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [ ]:
#selection of data
df['Age'].head(3)

0    23
1    25
2    63
Name: Age, dtype: int64

In [ ]:
df[['Age','Gender']].tail()

   Age Gender
0   23      M
1   25      M
2   63      M
3   22      M
4   20      F

In [ ]:
df.loc[0]

Name      Ajay
Age         23
Gender       M
Name: 0, dtype: object