<a href="https://colab.research.google.com/github/DeepuKun/Machine-Learning-Practice/blob/main/pandasDay2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = {
    "Name" : ["Ajay" , "Alex", "Arun" , "Aman", "Anam"],
    "Age" : [23,25,63,22,20]
}

In [3]:
df = pd.DataFrame(data)
df.head()

   Name  Age
0  Ajay   23
1  Alex   25
2  Arun   63
3  Aman   22
4  Anam   20

In [4]:
df = pd.read_csv("datasets/data.csv", encoding="latin-1")

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [6]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
7995,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
7996,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
7997,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
7998,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
7999,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [7]:
df.loc[0]

InvoiceNo                                  536365
StockCode                                  85123A
Description    WHITE HANGING HEART T-LIGHT HOLDER
Quantity                                        6
InvoiceDate                        12/1/2010 8:26
UnitPrice                                    2.55
CustomerID                                17850.0
Country                            United Kingdom
Name: 0, dtype: object

In [8]:
df.loc[0:5,'InvoiceNo':'UnitPrice']
# from 0 to 5 row and InvoiceNo to UnitPrice coloums

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65

# Completing the Day 2 topics
The four topics listed in class are worked through below on the Online-Retail invoice data (`df`).

## 1. Indexing and slicing

In [9]:
df['Description'].head()                       # one column -> Series

0     WHITE HANGING HEART T-LIGHT HOLDER
1                    WHITE METAL LANTERN
2         CREAM CUPID HEARTS COAT HANGER
3    KNITTED UNION FLAG HOT WATER BOTTLE
4         RED WOOLLY HOTTIE WHITE HEART.
Name: Description, dtype: str

In [10]:
df[['InvoiceNo', 'Quantity', 'UnitPrice']].head()   # several columns -> DataFrame

  InvoiceNo  Quantity  UnitPrice
0    536365         6       2.55
1    536365         6       3.39
2    536365         8       2.75
3    536365         6       3.39
4    536365         6       3.39

In [11]:
df.iloc[10:15]                                  # rows 10-14 by position (end excluded)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
10,536414,85099B,JUMBO BAG RED RETROSPOT,4,12/2/2010 8:54,1.95,15118.0,United Kingdom
11,536414,21754,HOME BUILDING BLOCK WORD,8,12/2/2010 8:54,5.95,15118.0,United Kingdom
12,536414,21754,HOME BUILDING BLOCK WORD,2,12/2/2010 8:54,5.95,15118.0,United Kingdom
13,536474,21212,PACK OF 72 RETROSPOT CAKE CASES,6,12/2/2010 17:31,0.55,15492.0,United Kingdom
14,536474,84406B,CREAM CUPID HEARTS COAT HANGER,24,12/2/2010 17:31,2.75,15492.0,United Kingdom

In [12]:
df.iloc[0:5, 0:3]                               # first 5 rows, first 3 columns

  InvoiceNo StockCode                          Description
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1    536365     71053                  WHITE METAL LANTERN
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.

In [13]:
df.iloc[-3:]                                    # last 3 rows

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
7997,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
7998,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
7999,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [14]:
df.loc[100:104, ['Description', 'Country']]     # label-based (end included)

                   Description         Country
100         RABBIT NIGHT LIGHT  United Kingdom
101   REGENCY CAKESTAND 3 TIER  United Kingdom
102  POPPY'S PLAYHOUSE KITCHEN  United Kingdom
103         RABBIT NIGHT LIGHT  United Kingdom
104  POPPY'S PLAYHOUSE BEDROOM  United Kingdom

In [15]:
print(df.at[0, 'Description'], '|', df.iat[0, 3])   # single values

WHITE HANGING HEART T-LIGHT HOLDER | 6

In [16]:
df.set_index('InvoiceNo').loc['536365']        # index by invoice number

,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
InvoiceNo,,,,,,,
536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom

## 2. Adding and modifying data

In [17]:
import numpy as np

retail = df.copy()
retail['TotalPrice'] = retail['Quantity'] * retail['UnitPrice']          # new column from existing ones
retail['InvoiceDate'] = pd.to_datetime(retail['InvoiceDate'], format='%m/%d/%Y %H:%M')
retail['Month'] = retail['InvoiceDate'].dt.to_period('M')
retail['IsCancelled'] = retail['InvoiceNo'].astype(str).str.startswith('C')
retail[['InvoiceNo', 'Quantity', 'UnitPrice', 'TotalPrice', 'Month', 'IsCancelled']].head()

  InvoiceNo  Quantity  UnitPrice  TotalPrice    Month  IsCancelled
0    536365         6       2.55       15.30  2010-12        False
1    536365         6       3.39       20.34  2010-12        False
2    536365         8       2.75       22.00  2010-12        False
3    536365         6       3.39       20.34  2010-12        False
4    536365         6       3.39       20.34  2010-12        False

In [18]:
retail.loc[retail['StockCode'] == 'POST', 'Description'] = 'POSTAGE CHARGE'   # conditional modify
retail['Description'] = retail['Description'].str.strip()
retail = retail.rename(columns={'UnitPrice': 'Price'})
retail.loc[len(retail)] = ['999999', 'TEST', 'MANUAL TEST ROW', 1, pd.Timestamp('2011-12-10'), 0.0, np.nan,
                           'United Kingdom', 0.0, pd.Period('2011-12', 'M'), False]            # add a row
retail.tail(2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country,TotalPrice,Month,IsCancelled
7999,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,2011-12,False
8000,999999,TEST,MANUAL TEST ROW,1,2011-12-10 00:00:00,0.00,NaN,United Kingdom,0.00,2011-12,False

In [19]:
retail = retail.drop(index=retail.index[-1])            # delete that test row
retail = retail.drop(columns=['IsCancelled'])           # delete a column
retail.shape

(8000, 10)

## 3. Handling missing values

In [20]:
retail.isnull().sum()

InvoiceNo         0
StockCode         0
Description      92
Quantity          0
InvoiceDate       0
Price             0
CustomerID     1644
Country           0
TotalPrice        0
Month             0
dtype: int64

In [21]:
print('% missing CustomerID:', round(retail['CustomerID'].isnull().mean() * 100, 2))

% missing CustomerID: 20.55

In [22]:
retail['Description'] = retail['Description'].fillna('UNKNOWN')          # fill text
with_customer = retail.dropna(subset=['CustomerID']).copy()               # drop rows missing the key
with_customer['CustomerID'] = with_customer['CustomerID'].astype(int)
print('rows before:', len(retail), '| after dropping missing CustomerID:', len(with_customer))
with_customer.isnull().sum()

rows before: 8000 | after dropping missing CustomerID: 6356

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
CustomerID     0
Country        0
TotalPrice     0
Month          0
dtype: int64

## 4. Sorting and filtering

In [23]:
with_customer.sort_values(by='TotalPrice', ascending=False).head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country,TotalPrice,Month
3706,555013,22423,REGENCY CAKESTAND 3 TIER,48,2011-05-17 08:13:00,12.75,15564,United Kingdom,612.0,2011-05
1255,542844,22423,REGENCY CAKESTAND 3 TIER,48,2011-01-28 08:19:00,12.75,14354,United Kingdom,612.0,2011-01
1086,541763,22423,REGENCY CAKESTAND 3 TIER,48,2011-01-19 17:15:00,12.75,15540,United Kingdom,612.0,2011-01
101,537043,22423,REGENCY CAKESTAND 3 TIER,48,2010-12-06 16:32:00,12.75,17741,United Kingdom,612.0,2010-12
1259,542844,22423,REGENCY CAKESTAND 3 TIER,48,2011-01-28 08:19:00,12.75,14354,United Kingdom,612.0,2011-01

In [24]:
with_customer.sort_values(by=['Country', 'InvoiceDate'], ascending=[True, False]).head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country,TotalPrice,Month
7480,573853,84029E,RED WOOLLY HOTTIE WHITE HEART.,8,2011-10-24 18:01:00,3.39,15218,Australia,27.12,2011-10
7481,573853,22633,HAND WARMER UNION JACK,12,2011-10-24 18:01:00,1.85,15218,Australia,22.20,2011-10
7482,573853,22748,POPPY'S PLAYHOUSE KITCHEN,4,2011-10-24 18:01:00,2.10,15218,Australia,8.40,2011-10
7483,573853,22310,IVORY KNITTED MUG COSY,1,2011-10-24 18:01:00,1.65,15218,Australia,1.65,2011-10
7484,573853,21755,LOVE BUILDING BLOCK WORD,6,2011-10-24 18:01:00,5.95,15218,Australia,35.70,2011-10

In [25]:
with_customer[with_customer['Quantity'] < 0].head()          # cancelled orders

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country,TotalPrice,Month
150,C537254,21755,LOVE BUILDING BLOCK WORD,-4,2010-12-09 08:13:00,5.95,14744,United Kingdom,-23.80,2010-12
151,C537254,85123A,WHITE HANGING HEART T-LIGHT HOLDER,-48,2010-12-09 08:13:00,2.55,14744,United Kingdom,-122.40,2010-12
152,C537254,22913,RED COAT RACK PARIS FASHION,-4,2010-12-09 08:13:00,4.95,14744,United Kingdom,-19.80,2010-12
153,C537254,22632,HAND WARMER RED POLKA DOT,-6,2010-12-09 08:13:00,1.85,14744,United Kingdom,-11.10,2010-12
154,C537254,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,-3,2010-12-09 08:13:00,3.39,14744,United Kingdom,-10.17,2010-12

In [26]:
with_customer[(with_customer['Country'] == 'France') & (with_customer['Quantity'] >= 12)].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country,TotalPrice,Month
1688,544777,21212,PACK OF 72 RETROSPOT CAKE CASES,24,2011-02-14 15:19:00,0.55,14636,France,13.2,2011-02
1690,544777,47566,PARTY BUNTING,24,2011-02-14 15:19:00,4.95,14636,France,118.8,2011-02
1691,544777,22960,JAM MAKING SET WITH JARS,48,2011-02-14 15:19:00,4.25,14636,France,204.0,2011-02
3060,551569,21754,HOME BUILDING BLOCK WORD,24,2011-04-15 17:19:00,5.95,13403,France,142.8,2011-04
4451,558476,22423,REGENCY CAKESTAND 3 TIER,12,2011-06-17 09:14:00,12.75,12828,France,153.0,2011-06

In [27]:
with_customer[with_customer['Country'].isin(['Germany', 'EIRE'])].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country,TotalPrice,Month
367,538174,21755,LOVE BUILDING BLOCK WORD,1,2010-12-17 18:03:00,5.95,14403,EIRE,5.95,2010-12
368,538174,22752,SET 7 BABUSHKA NESTING BOXES,4,2010-12-17 18:03:00,7.65,14403,EIRE,30.60,2010-12
369,538174,22745,POPPY'S PLAYHOUSE BEDROOM,8,2010-12-17 18:03:00,2.10,14403,EIRE,16.80,2010-12
370,538174,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-17 18:03:00,2.75,14403,EIRE,22.00,2010-12
371,538174,47566,PARTY BUNTING,24,2010-12-17 18:03:00,4.95,14403,EIRE,118.80,2010-12

In [28]:
with_customer[with_customer['Description'].str.contains('HEART')].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country,TotalPrice,Month
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010-12
7,536414,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2010-12-02 08:54:00,2.55,15118,United Kingdom,20.40,2010-12
9,536414,21777,RECIPE BOX WITH METAL HEART,8,2010-12-02 08:54:00,7.95,15118,United Kingdom,63.60,2010-12

In [29]:
with_customer.query('Price > 10 and Quantity > 0').head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country,TotalPrice,Month
34,536552,22423,REGENCY CAKESTAND 3 TIER,2,2010-12-03 08:42:00,12.75,17517,United Kingdom,25.5,2010-12
35,536552,22423,REGENCY CAKESTAND 3 TIER,4,2010-12-03 08:42:00,12.75,17517,United Kingdom,51.0,2010-12
66,536735,22423,REGENCY CAKESTAND 3 TIER,6,2010-12-04 09:31:00,12.75,15217,United Kingdom,76.5,2010-12
101,537043,22423,REGENCY CAKESTAND 3 TIER,48,2010-12-06 16:32:00,12.75,17741,United Kingdom,612.0,2010-12
123,537166,22423,REGENCY CAKESTAND 3 TIER,6,2010-12-08 08:17:00,12.75,15088,United Kingdom,76.5,2010-12

In [30]:
# Putting it together: revenue by country from valid (non-cancelled) orders
valid = with_customer[with_customer['Quantity'] > 0]
valid.groupby('Country')['TotalPrice'].sum().sort_values(ascending=False).head(5).round(2)

Country
United Kingdom    272223.87
Germany             5914.39
EIRE                5527.23
France              1898.99
Switzerland         1430.41
Name: TotalPrice, dtype: float64