# Pandas for Data Science
Pandas gives us the **Series** (1-D) and the **DataFrame** (2-D table), which is the main tool for loading,
cleaning, transforming and summarising data before visualisation or machine learning.

**Dataset used:** `datasets/students_performance.csv` records 60 students (department, city, study hours,
attendance and marks). It is deliberately messy, with missing values, duplicate rows and inconsistent city spellings,
so every cleaning step has something to do. `datasets/departments.csv` is a second small table used for merging.

**Contents**
1. Series & DataFrame creation
2. Reading data (CSV)
3. Inspecting data
4. Selecting data: `[]`, `loc`, `iloc`, `at`/`iat`
5. Adding / modifying / deleting columns
6. Handling missing values
7. Duplicates
8. Cleaning text columns
9. Sorting & filtering
10. GroupBy & aggregation
11. Apply / map
12. Merging & concatenating
13. Pivot tables & crosstabs
14. Saving data

In [1]:
import numpy as np
import pandas as pd
print('Pandas version:', pd.__version__)

Pandas version: 3.0.2

## 1. Series & DataFrame creation

In [2]:
s = pd.Series([23, 25, 63, 22, 20], index=['Ajay', 'Alex', 'Arun', 'Aman', 'Anam'], name='Age')
s

Ajay    23
Alex    25
Arun    63
Aman    22
Anam    20
Name: Age, dtype: int64

In [3]:
print(s['Arun'], s.iloc[0], s.mean())
s[s > 22]

63 23 30.6

Ajay    23
Alex    25
Arun    63
Name: Age, dtype: int64

In [4]:
data = {
    'Name':   ['Ajay', 'Alex', 'Arun', 'Aman', 'Anam'],
    'Age':    [23, 25, 63, 22, 20],
    'Gender': ['M', 'M', 'M', 'M', 'F'],
}
pd.DataFrame(data)

   Name  Age Gender
0  Ajay   23      M
1  Alex   25      M
2  Arun   63      M
3  Aman   22      M
4  Anam   20      F

In [5]:
# A DataFrame from a list of rows
pd.DataFrame([[1, 'Maths', 78], [2, 'Physics', 85]], columns=['Roll', 'Subject', 'Marks'])

   Roll  Subject  Marks
0     1    Maths     78
1     2  Physics     85

## 2. Reading data

In [6]:
df = pd.read_csv('datasets/students_performance.csv')
df.head()

,Student_ID,Name,Gender,Age,City,Department,Study_Hours,Attendance,Maths,Physics,Chemistry
0,S001,Nisha Kapoor,F,20.0,Hyderabad,AIML,19,78.0,79.0,66.0,73
1,S002,Harsh Gupta,M,20.0,Bangalore,CSE,10,87.0,65.0,50.0,56
2,S003,Anjali Pillai,F,18.0,Chennai,MECH,17,73.0,51.0,65.0,54
3,S004,Aarav Gupta,M,19.0,chennai,ECE,11,79.0,56.0,58.0,41
4,S005,Ananya Verma,F,21.0,Chennai,MECH,5,NaN,42.0,49.0,55

## 3. Inspecting data

In [7]:
print('shape  :', df.shape)
print('columns:', df.columns.tolist())

shape  : (63, 11)
columns: ['Student_ID', 'Name', 'Gender', 'Age', 'City', 'Department', 'Study_Hours', 'Attendance', 'Maths', 'Physics', 'Chemistry']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_ID   63 non-null     str
 1   Name         63 non-null     str
 2   Gender       63 non-null     str
 3   Age          60 non-null     float64
 4   City         61 non-null     str
 5   Department   63 non-null     str
 6   Study_Hours  63 non-null     int64
 7   Attendance   60 non-null     float64
 8   Maths        61 non-null     float64
 9   Physics      62 non-null     float64
 10  Chemistry    63 non-null     int64
dtypes: float64(4), int64(2), str(5)
memory usage: 7.2 KB

In [9]:
df.describe()

             Age  Study_Hours  Attendance       Maths    Physics  Chemistry
count  60.000000    63.000000   60.000000   61.000000  62.000000  63.000000
mean   19.866667    11.095238   84.366667   62.950820  59.935484  56.142857
std     1.431683     4.888150    9.665537   15.962901  14.245932  13.403005
min    18.000000     2.000000   63.000000   15.000000  32.000000  30.000000
25%    19.000000     7.500000   77.750000   54.000000  50.000000  47.000000
50%    20.000000    10.000000   84.000000   60.000000  61.000000  55.000000
75%    21.000000    15.000000   91.000000   74.000000  70.000000  65.000000
max    22.000000    19.000000  100.000000  100.000000  94.000000  84.000000

In [10]:
df.describe(include='object')

C:\Users\ratta\AppData\Local\Temp\ipykernel_23392\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

       Student_ID          Name Gender       City Department
count          63            63     63         61         63
unique         60            57      2         12          4
top          S006  Ira Kulkarni      F  Hyderabad        CSE
freq            2             2     33         13         21

In [11]:
df.tail(3)

,Student_ID,Name,Gender,Age,City,Department,Study_Hours,Attendance,Maths,Physics,Chemistry
60,S006,Ira Kulkarni,F,19.0,Bangalore,ECE,18,74.0,71.0,83.0,54
61,S020,Pooja Nair,F,18.0,Chennai,MECH,15,100.0,73.0,74.0,62
62,S031,Krishna Chopra,M,21.0,Hyderabad,MECH,10,91.0,60.0,61.0,56

In [12]:
df['Department'].value_counts()

Department
CSE     21
MECH    18
AIML    15
ECE      9
Name: count, dtype: int64

In [13]:
df.nunique()

Student_ID     60
Name           57
Gender          2
Age             5
City           12
Department      4
Study_Hours    18
Attendance     29
Maths          33
Physics        32
Chemistry      35
dtype: int64

## 4. Selecting data
- `df['col']` gives a column (Series), and `df[['a','b']]` gives a DataFrame
- `loc` selects by **label**, and the end is inclusive
- `iloc` selects by **integer position**, and the end is exclusive
- `at` / `iat` read or write a single value quickly

In [14]:
df['Name'].head(3)

0     Nisha Kapoor
1      Harsh Gupta
2    Anjali Pillai
Name: Name, dtype: str

In [15]:
df[['Name', 'Department', 'Maths']].head(3)

            Name Department  Maths
0   Nisha Kapoor       AIML   79.0
1    Harsh Gupta        CSE   65.0
2  Anjali Pillai       MECH   51.0

In [16]:
df.loc[0]

Student_ID             S001
Name           Nisha Kapoor
Gender                    F
Age                    20.0
City              Hyderabad
Department             AIML
Study_Hours              19
Attendance             78.0
Maths                  79.0
Physics                66.0
Chemistry                73
Name: 0, dtype: object

In [17]:
df.loc[0:4, 'Name':'City']      # rows 0-4 INCLUDED

            Name Gender   Age       City
0   Nisha Kapoor      F  20.0  Hyderabad
1    Harsh Gupta      M  20.0  Bangalore
2  Anjali Pillai      F  18.0    Chennai
3    Aarav Gupta      M  19.0    chennai
4   Ananya Verma      F  21.0    Chennai

In [18]:
df.iloc[0:5, [1, 3, 8]]           # rows 0-4, columns by position

            Name   Age  Maths
0   Nisha Kapoor  20.0   79.0
1    Harsh Gupta  20.0   65.0
2  Anjali Pillai  18.0   51.0
3    Aarav Gupta  19.0   56.0
4   Ananya Verma  21.0   42.0

In [19]:
df.loc[df['Department'] == 'AIML', ['Name', 'Maths', 'Physics']].head()

             Name  Maths  Physics
0    Nisha Kapoor   79.0     66.0
7     Aryan Patel   63.0     63.0
15  Ananya Chopra   54.0     54.0
16    Arjun Patel   62.0     49.0
20   Reyansh Nair  100.0     68.0

In [20]:
print(df.at[0, 'Name'], '|', df.iat[0, 1])

Nisha Kapoor | Nisha Kapoor

In [21]:
# Setting a meaningful index
by_id = df.set_index('Student_ID')
by_id.loc['S005']

Name           Ananya Verma
Gender                    F
Age                    21.0
City                Chennai
Department             MECH
Study_Hours               5
Attendance              NaN
Maths                  42.0
Physics                49.0
Chemistry                55
Name: S005, dtype: object

## 5. Adding / modifying / deleting columns

In [22]:
students = df.copy()                                   # never modify the raw data
students['Total'] = students[['Maths', 'Physics', 'Chemistry']].sum(axis=1, min_count=3)
students['Percentage'] = (students['Total'] / 300 * 100).round(2)
students.insert(2, 'Batch', 2024)                       # insert at a chosen position
students.head()

,Student_ID,Name,Batch,Gender,Age,City,Department,Study_Hours,Attendance,Maths,Physics,Chemistry,Total,Percentage
0,S001,Nisha Kapoor,2024,F,20.0,Hyderabad,AIML,19,78.0,79.0,66.0,73,218.0,72.67
1,S002,Harsh Gupta,2024,M,20.0,Bangalore,CSE,10,87.0,65.0,50.0,56,171.0,57.00
2,S003,Anjali Pillai,2024,F,18.0,Chennai,MECH,17,73.0,51.0,65.0,54,170.0,56.67
3,S004,Aarav Gupta,2024,M,19.0,chennai,ECE,11,79.0,56.0,58.0,41,155.0,51.67
4,S005,Ananya Verma,2024,F,21.0,Chennai,MECH,5,NaN,42.0,49.0,55,146.0,48.67

In [23]:
students.loc[students['Student_ID'] == 'S001', 'Study_Hours'] = 13     # modify one value
students = students.rename(columns={'Study_Hours': 'Weekly_Study_Hours'})
students = students.drop(columns=['Batch'])
students.columns.tolist()

['Student_ID',
 'Name',
 'Gender',
 'Age',
 'City',
 'Department',
 'Weekly_Study_Hours',
 'Attendance',
 'Maths',
 'Physics',
 'Chemistry',
 'Total',
 'Percentage']

## 6. Handling missing values

In [24]:
students.isnull().sum()

Student_ID            0
Name                  0
Gender                0
Age                   3
City                  2
Department            0
Weekly_Study_Hours    0
Attendance            3
Maths                 2
Physics               1
Chemistry             0
Total                 3
Percentage            3
dtype: int64

In [25]:
students[students.isnull().any(axis=1)]

,Student_ID,Name,Gender,Age,City,Department,Weekly_Study_Hours,Attendance,Maths,Physics,Chemistry,Total,Percentage
4,S005,Ananya Verma,F,21.0,Chennai,MECH,5,NaN,42.0,49.0,55,146.0,48.67
7,S008,Aryan Patel,M,NaN,Chennai,AIML,9,97.0,63.0,63.0,55,181.0,60.33
12,S013,Aarav Kapoor,M,18.0,Bangalore,CSE,9,66.0,NaN,43.0,36,NaN,NaN
15,S016,Ananya Chopra,F,22.0,NaN,AIML,13,84.0,54.0,54.0,65,173.0,57.67
22,S023,Neha Bose,F,22.0,Kolkata,CSE,15,NaN,75.0,66.0,61,202.0,67.33
27,S028,Harsh Nair,M,19.0,Bangalore,AIML,4,81.0,42.0,NaN,38,NaN,NaN
33,S034,Simran Mehta,F,NaN,Kolkata,CSE,7,87.0,51.0,61.0,38,150.0,50.00
38,S039,Kabir Singh,M,18.0,Hyderabad,CSE,9,99.0,NaN,63.0,57,NaN,NaN
40,S041,Nikhil Bose,M,22.0,NaN,AIML,17,92.0,99.0,74.0,70,243.0,81.00
45,S046,Karan Kulkarni,M,20.0,Kolkata,AIML,9,NaN,76.0,63.0,46,185.0,61.67
51,S052,Rohan Reddy,M,NaN,Bangalore,MECH,9,64.0,57.0,50.0,55,162.0,54.00

In [26]:
# Strategy per column
students['Age'] = students['Age'].fillna(students['Age'].median())
students['Attendance'] = students['Attendance'].fillna(students['Attendance'].mean().round(1))
students['City'] = students['City'].fillna(students['City'].mode()[0])
# Marks: fill with that department's median, which is fairer than a global value
for col in ['Maths', 'Physics']:
    students[col] = students[col].fillna(students.groupby('Department')[col].transform('median'))
students['Total'] = students[['Maths', 'Physics', 'Chemistry']].sum(axis=1)
students['Percentage'] = (students['Total'] / 300 * 100).round(2)
students.isnull().sum().sum()

np.int64(0)

In [27]:
# The alternative: drop rows instead of filling
print('rows before dropna:', len(df), '| after:', len(df.dropna()))

rows before dropna: 63 | after: 52

## 7. Duplicates

In [28]:
print('duplicate rows:', students.duplicated().sum())
students[students.duplicated(keep=False)].sort_values('Student_ID')

duplicate rows: 3

,Student_ID,Name,Gender,Age,City,Department,Weekly_Study_Hours,Attendance,Maths,Physics,Chemistry,Total,Percentage
5,S006,Ira Kulkarni,F,19.0,Bangalore,ECE,18,74.0,71.0,83.0,54,208.0,69.33
60,S006,Ira Kulkarni,F,19.0,Bangalore,ECE,18,74.0,71.0,83.0,54,208.0,69.33
19,S020,Pooja Nair,F,18.0,Chennai,MECH,15,100.0,73.0,74.0,62,209.0,69.67
61,S020,Pooja Nair,F,18.0,Chennai,MECH,15,100.0,73.0,74.0,62,209.0,69.67
30,S031,Krishna Chopra,M,21.0,Hyderabad,MECH,10,91.0,60.0,61.0,56,177.0,59.00
62,S031,Krishna Chopra,M,21.0,Hyderabad,MECH,10,91.0,60.0,61.0,56,177.0,59.00

In [29]:
students = students.drop_duplicates().reset_index(drop=True)
students.shape

(60, 13)

## 8. Cleaning text columns
The same city is spelled in different ways, which would split it into separate groups.

In [30]:
students['City'].value_counts()

City
Hyderabad     14
Chennai       11
Kolkata       11
Mumbai         9
Bangalore      6
Delhi          3
chennai        1
 Delhi         1
MUMBAI         1
bangalore      1
hyderabad      1
Chennai        1
Name: count, dtype: int64

In [31]:
students['City'] = students['City'].str.strip().str.title()
students['Name'] = students['Name'].str.strip()
students['First_Name'] = students['Name'].str.split().str[0]
students['City'].value_counts()

City
Hyderabad    15
Chennai      13
Kolkata      11
Mumbai       10
Bangalore     7
Delhi         4
Name: count, dtype: int64

## 9. Sorting & filtering

In [32]:
students.sort_values(by='Percentage', ascending=False).head()

,Student_ID,Name,Gender,Age,City,Department,Weekly_Study_Hours,Attendance,Maths,Physics,Chemistry,Total,Percentage,First_Name
18,S019,Rohan Kapoor,M,21.0,Mumbai,CSE,19,100.0,90.0,94.0,84,268.0,89.33,Rohan
20,S021,Reyansh Nair,M,19.0,Delhi,AIML,19,90.0,100.0,68.0,77,245.0,81.67,Reyansh
40,S041,Nikhil Bose,M,22.0,Hyderabad,AIML,17,92.0,99.0,74.0,70,243.0,81.00,Nikhil
34,S035,Sneha Nair,F,19.0,Mumbai,CSE,15,100.0,78.0,83.0,78,239.0,79.67,Sneha
48,S049,Aisha Chopra,F,18.0,Chennai,AIML,15,96.0,92.0,70.0,77,239.0,79.67,Aisha

In [33]:
students.sort_values(by=['Department', 'Maths'], ascending=[True, False]).head()

,Student_ID,Name,Gender,Age,City,Department,Weekly_Study_Hours,Attendance,Maths,Physics,Chemistry,Total,Percentage,First_Name
20,S021,Reyansh Nair,M,19.0,Delhi,AIML,19,90.0,100.0,68.0,77,245.0,81.67,Reyansh
40,S041,Nikhil Bose,M,22.0,Hyderabad,AIML,17,92.0,99.0,74.0,70,243.0,81.00,Nikhil
48,S049,Aisha Chopra,F,18.0,Chennai,AIML,15,96.0,92.0,70.0,77,239.0,79.67,Aisha
0,S001,Nisha Kapoor,F,20.0,Hyderabad,AIML,13,78.0,79.0,66.0,73,218.0,72.67,Nisha
39,S040,Sneha Sharma,F,18.0,Chennai,AIML,17,84.0,79.0,74.0,57,210.0,70.00,Sneha

In [34]:
students[(students['Attendance'] < 75) & (students['Percentage'] < 60)]      # at-risk students

,Student_ID,Name,Gender,Age,City,Department,Weekly_Study_Hours,Attendance,Maths,Physics,Chemistry,Total,Percentage,First_Name
2,S003,Anjali Pillai,F,18.0,Chennai,MECH,17,73.0,51.0,65.0,54,170.0,56.67,Anjali
12,S013,Aarav Kapoor,M,18.0,Bangalore,CSE,9,66.0,60.0,43.0,36,139.0,46.33,Aarav
16,S017,Arjun Patel,M,19.0,Mumbai,AIML,8,74.0,62.0,49.0,32,143.0,47.67,Arjun
26,S027,Vivaan Rao,M,21.0,Bangalore,CSE,8,73.0,53.0,54.0,30,137.0,45.67,Vivaan
31,S032,Sneha Nair,F,19.0,Hyderabad,ECE,9,63.0,15.0,39.0,54,108.0,36.00,Sneha
35,S036,Diya Reddy,F,21.0,Kolkata,AIML,11,73.0,59.0,52.0,62,173.0,57.67,Diya
42,S043,Ishaan Patel,M,19.0,Kolkata,MECH,7,73.0,54.0,58.0,45,157.0,52.33,Ishaan
43,S044,Myra Verma,F,20.0,Kolkata,CSE,9,70.0,54.0,61.0,54,169.0,56.33,Myra
51,S052,Rohan Reddy,M,20.0,Bangalore,MECH,9,64.0,57.0,50.0,55,162.0,54.00,Rohan

In [35]:
students[students['City'].isin(['Chennai', 'Delhi'])].head()

,Student_ID,Name,Gender,Age,City,Department,Weekly_Study_Hours,Attendance,Maths,Physics,Chemistry,Total,Percentage,First_Name
2,S003,Anjali Pillai,F,18.0,Chennai,MECH,17,73.0,51.0,65.0,54,170.0,56.67,Anjali
3,S004,Aarav Gupta,M,19.0,Chennai,ECE,11,79.0,56.0,58.0,41,155.0,51.67,Aarav
4,S005,Ananya Verma,F,21.0,Chennai,MECH,5,84.4,42.0,49.0,55,146.0,48.67,Ananya
6,S007,Meera Joshi,F,19.0,Chennai,ECE,18,94.0,70.0,81.0,84,235.0,78.33,Meera
7,S008,Aryan Patel,M,20.0,Chennai,AIML,9,97.0,63.0,63.0,55,181.0,60.33,Aryan

In [36]:
students[students['Weekly_Study_Hours'].between(15, 20)][['Name', 'Weekly_Study_Hours', 'Percentage']]

             Name  Weekly_Study_Hours  Percentage
2   Anjali Pillai                  17       56.67
5    Ira Kulkarni                  18       69.33
6     Meera Joshi                  18       78.33
10   Aadhya Mehta                  19       76.00
14   Aadhya Patel                  19       75.67
18   Rohan Kapoor                  19       89.33
19     Pooja Nair                  15       69.67
20   Reyansh Nair                  19       81.67
22      Neha Bose                  15       67.33
34     Sneha Nair                  15       79.67
39   Sneha Sharma                  17       70.00
40    Nikhil Bose                  17       81.00
48   Aisha Chopra                  15       79.67
49   Aadhya Patel                  19       73.67
53     Meera Bose                  15       72.33
55    Riya Chopra                  16       71.33

In [37]:
students.query('Department == "CSE" and Maths >= 80')

,Student_ID,Name,Gender,Age,City,Department,Weekly_Study_Hours,Attendance,Maths,Physics,Chemistry,Total,Percentage,First_Name
9,S010,Manav Verma,M,19.0,Delhi,CSE,14,98.0,85.0,70.0,68,223.0,74.33,Manav
18,S019,Rohan Kapoor,M,21.0,Mumbai,CSE,19,100.0,90.0,94.0,84,268.0,89.33,Rohan
53,S054,Meera Bose,F,22.0,Mumbai,CSE,15,96.0,84.0,65.0,68,217.0,72.33,Meera

In [38]:
students.nlargest(3, 'Total')[['Name', 'Department', 'Total']]

            Name Department  Total
18  Rohan Kapoor        CSE  268.0
20  Reyansh Nair       AIML  245.0
40   Nikhil Bose       AIML  243.0

## 10. GroupBy & aggregation

In [39]:
students.groupby('Department')['Percentage'].mean().round(2).sort_values(ascending=False)

Department
AIML    61.94
CSE     60.63
MECH    57.38
ECE     55.04
Name: Percentage, dtype: float64

In [40]:
students.groupby('Department').agg(
    students=('Student_ID', 'count'),
    avg_hours=('Weekly_Study_Hours', 'mean'),
    avg_attendance=('Attendance', 'mean'),
    avg_percentage=('Percentage', 'mean'),
    topper_total=('Total', 'max'),
).round(2)

            students  avg_hours  avg_attendance  avg_percentage  topper_total
Department
AIML              15      10.87           85.89           61.94         245.0
CSE               21      10.81           85.45           60.63         268.0
ECE                8      11.12           83.12           55.04         235.0
MECH              16      10.69           81.40           57.38         228.0

In [41]:
students.groupby(['Department', 'Gender'])['Percentage'].mean().unstack().round(2)

Gender          F      M
Department
AIML        60.13  64.00
CSE         62.56  59.19
ECE         52.47  59.33
MECH        60.07  53.90

## 11. Apply / map

In [42]:
def grade(p):
    if p >= 85: return 'A'
    if p >= 70: return 'B'
    if p >= 55: return 'C'
    if p >= 40: return 'D'
    return 'F'

students['Grade'] = students['Percentage'].apply(grade)
students['Gender_Full'] = students['Gender'].map({'M': 'Male', 'F': 'Female'})
students['Hours_Band'] = pd.cut(students['Weekly_Study_Hours'], bins=[0, 6, 12, 25], labels=['Low', 'Medium', 'High'])
students[['Name', 'Percentage', 'Grade', 'Gender_Full', 'Hours_Band']].head()

            Name  Percentage Grade Gender_Full Hours_Band
0   Nisha Kapoor       72.67     B      Female       High
1    Harsh Gupta       57.00     C        Male     Medium
2  Anjali Pillai       56.67     C      Female       High
3    Aarav Gupta       51.67     D        Male     Medium
4   Ananya Verma       48.67     D      Female        Low

In [43]:
students['Grade'].value_counts().sort_index()

Grade
A     1
B    15
C    17
D    25
F     2
Name: count, dtype: int64

## 12. Merging & concatenating

In [44]:
depts = pd.read_csv('datasets/departments.csv')
depts

,Department,Dept_Name,HOD,Block
0,CSE,Computer Science & Engineering,Dr. R. Kumar,Tech Park
1,ECE,Electronics & Communication,Dr. S. Lakshmi,Main Block
2,MECH,Mechanical Engineering,Dr. P. Anand,Workshop Block
3,AIML,Artificial Intelligence & Machine Learning,Dr. M. Fernandes,Tech Park

In [45]:
merged = students.merge(depts, on='Department', how='left')
merged[['Name', 'Department', 'Dept_Name', 'HOD', 'Block']].head()

,Name,Department,Dept_Name,HOD,Block
0,Nisha Kapoor,AIML,Artificial Intelligence & Machine Learning,Dr. M. Fernandes,Tech Park
1,Harsh Gupta,CSE,Computer Science & Engineering,Dr. R. Kumar,Tech Park
2,Anjali Pillai,MECH,Mechanical Engineering,Dr. P. Anand,Workshop Block
3,Aarav Gupta,ECE,Electronics & Communication,Dr. S. Lakshmi,Main Block
4,Ananya Verma,MECH,Mechanical Engineering,Dr. P. Anand,Workshop Block

In [46]:
new_admissions = pd.DataFrame({'Student_ID': ['S061', 'S062'], 'Name': ['Kiara Das', 'Vihaan Rao'],
                               'Department': ['AIML', 'CSE']})
pd.concat([students[['Student_ID', 'Name', 'Department']].tail(2), new_admissions], ignore_index=True)

  Student_ID         Name Department
0       S059  Shreya Bose        ECE
1       S060   Yash Singh        CSE
2       S061    Kiara Das       AIML
3       S062   Vihaan Rao        CSE

## 13. Pivot tables & crosstabs

In [47]:
pd.pivot_table(students, values='Percentage', index='Department', columns='Gender', aggfunc='mean').round(2)

Gender          F      M
Department
AIML        60.13  64.00
CSE         62.56  59.19
ECE         52.47  59.33
MECH        60.07  53.90

In [48]:
pd.crosstab(students['Department'], students['Grade'])

Grade       A  B  C   D  F
Department
AIML        0  5  5   5  0
CSE         1  5  5  10  0
ECE         0  2  2   2  2
MECH        0  3  5   8  0

## 14. Saving data

In [49]:
# students.to_csv('datasets/students_cleaned.csv', index=False)   # uncomment to write the cleaned file
print(students.to_csv(index=False)[:250])

Student_ID,Name,Gender,Age,City,Department,Weekly_Study_Hours,Attendance,Maths,Physics,Chemistry,Total,Percentage,First_Name,Grade,Gender_Full,Hours_Band
S001,Nisha Kapoor,F,20.0,Hyderabad,AIML,13,78.0,79.0,66.0,73,218.0,72.67,Nisha,B,Female,High
S

## Key takeaways
- Always start with `head()`, `info()`, `describe()` and `isnull().sum()`.
- `loc` includes the end label, while `iloc` excludes the end position.
- Choose imputation per column: median for skewed numbers, mode for categories, and group-wise values when groups differ.
- Clean text (`str.strip().str.title()`) **before** grouping, or one city becomes several.
- `groupby` + `agg` is the fastest way to answer "which X has the highest Y?"
- Work on a `.copy()` so the raw data is never modified by accident.